language: node_js
node_js:
  - "12.10.0"
after_success:
  - npm run build
  - npm install -g firebase-tools
  - firebase use hosting --token $FIREBASE_TOKEN --non-interactive
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive